### ISSUE TITLE
help

### ISSUE THREAD

**Issue by julimonsa0x** [Elastoo-Team/ethereum-gasprice-py#16]
Traceback (most recent call last):
  File "*******", line 1, in <module>
    from ethereum_gasprice import GaspriceController, GaspriceStrategy, EthereumUnit
ModuleNotFoundError: No module named 'ethereum_gasprice'

the quickstart isn't working for me, i did "pip install ethereum-gasprice==1.2.3" and "pip3 install ethereum-gasprice==1.2.3"
what else should i do??

**Comment by NikitosnikN** [comment]
Hi @julimonsa0x !

I guess you installed package incorrectly.

Try to reinstall package with `pip install ethereum-gasprice` (without version) and make sure that you activated the right environment.

**Comment by NikitosnikN** [comment]
closed due to inactivity

**Comment by julimonsa0x** [comment]
Sorry for late answer but it worked, I was using Repl.it btw
